spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AibasedHelpdeskdb?useSSL=false&serverTimezone=UTC
    username: root
    password: AAaa@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
#Gemini ai config
  ai:
    google:
      genai:
        api-key: ${API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
#            model: gemini-3-pro-preview
            temperature: 0.7
#            output token
#            max-output-tokens: 2000




  application:
    name: Ai-Based-Helpdesk


# Server port config
server:
  port: 8083

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

